name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  id-token: write

jobs:
  test-release:
    name: Test Release on TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/claif_gem
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.12"
          enable-cache: true

      - name: Install build tools
        run: uv pip install build hatchling hatch-vcs

      - name: Build distributions
        run: uv run python -m build --outdir dist

      - name: Verify distribution files
        run: |
          ls -la dist/
          test -n "$(find dist -name '*.whl')" || (echo "Wheel file missing" && exit 1)
          test -n "$(find dist -name '*.tar.gz')" || (echo "Source distribution missing" && exit 1)

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Test installation from TestPyPI
        run: |
          sleep 60  # Wait for package to be available
          uv pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ claif_gem
          python -c "import claif_gem; print(f'Successfully imported claif_gem version {claif_gem.__version__}')"

  release:
    name: Release to PyPI
    needs: test-release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/claif_gem
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.12"
          enable-cache: true

      - name: Install build tools
        run: uv pip install build hatchling hatch-vcs

      - name: Build distributions
        run: uv run python -m build --outdir dist

      - name: Verify distribution files
        run: |
          ls -la dist/
          test -n "$(find dist -name '*.whl')" || (echo "Wheel file missing" && exit 1)
          test -n "$(find dist -name '*.tar.gz')" || (echo "Source distribution missing" && exit 1)

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          body: |
            ## Installation
            
            ### Python Package
            ```bash
            pip install claif-gem
            ```
            
            ### Binary Installation
            Pre-compiled binaries are available in the assets below for Linux, Windows, and macOS.
            
            1. Download the appropriate binary for your platform
            2. Extract the archive 
            3. Move the binary to a directory in your PATH
            4. Make it executable (Linux/macOS): `chmod +x claif-gem`
            5. Run: `claif-gem --help`
            
            **Note**: Binary builds are triggered automatically after this release completes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 